server:
  port: 8095
spring:
  application:
    name: hangyi-statistics
  datasource:
    url: jdbc:mysql://localhost:3306/hangyi_scheduling?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.qyf.hangyi.statistics.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.qyf.hangyi.statistics: debug

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    nacos:
      discovery:
        enabled: false
